#!/bin/sh

xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto

/usr/bin/prime-offload

userresources=$XDG_CONFIG_HOME/X11/xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Setting mouse pointer to left arrow
xsetroot -cursor_name left_ptr &

# for uniform style across qt and gtk
export QT_QPA_PLATFORMTHEME=gtk2

# disabling some display access stuff
xhost +

# Keyboard Layout
setxkbmap en &

systemctl --user import-environment DISPLAY

# clipboard service
systemctl --user start clipmenud.service

# setting mouse to be faast
xset r rate 200 40

# screensaver
xscreensaver &

# compositor
picom -b &

# Starting WM
exec bspwm
