#! /bin/sh
################################################################################
# ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗
# ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
# ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
# ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
# ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
# ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝
################################################################################
# o┳━┓┳━┓┳━┓┳━┓o┏┓┓┳━┓┳━┓┳━┓┓ ┳
# ┃┃━┃┃━┫┃┳┛┃━┃┃ ┃ ┃┳┛┃━┫┃┳┛┗┏┛
# ┇┇━┛┛ ┇┇┗┛┇━┛┇ ┇ ┇┗┛┛ ┇┇┗┛ ┇
################################################################################
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d  ௧ ௨ ௩ ௪ ௫ ௬ ௭ ௮  ௯ ௦
# ௦ ௧ ௨ ௩ ௪ ௫ ௬ ௭ ௮  ௯ ௰
$HOME/.config/polybar/launch.sh

bspc config border_width         4
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=tiled follow=on
bspc rule -a Blender desktop='^7' state=tiled follow=on
bspc rule -a Inkscape desktop='^9' state=tiled follow=on
bspc rule -a krita desktop='^10' state=tiled follow=on
# bspc rule -a firefox desktop='^2' follow=on
bspc rule -a Zathura state=tiled follow=on
bspc rule -a Nitrogen state=floating
bspc rule -a Emacs state=tiled
bspc rule -a Yad state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Display state=floating
bspc rule -a feh state=floating
bspc rule -a Qalculate-gtk state=floating

bspc config focus_follows_pointer true

bspc config active_border_color \#282828
bspc config normal_border_color \#3c3836
bspc config focused_border_color \#d5c4a1

# wallpaper slideshow
bgchd -dir /media/storage/pictures/wallpapers/ -intv 5m -bcknd feh -rpl

# controlling players
playerctld daemon
