#! /usr/bin/env bash

status=$(systemctl is-active 'bluetooth.service')

#if [ "$stat" = "active" ]; then
#    status="on"
#elif [ "$stat" = "inactive" ]; then
#    status="off"
#fi

case "$1" in
    --toggle)
        if [ "$status" = "inactive" ]; then
            sudo systemctl start bluetooth.service;
            notify-send "Turned on Bluetooth service."
        elif [ "$status" = "active" ]; then
            sudo systemctl stop bluetooth.service;
            notify-send "Turned off Bluetooth service."
        fi
        ;;
    *)
        if [ "$status" = "inactive" ]; then
            echo "B₀"
        elif [ "$status" = "active" ]; then
            echo "B₁"
        fi
        ;;
esac
