#! /usr/bin/env bash

igpu=$(glxinfo | grep -oP "video memory: \K(\d+)(?=\sMB)")
itotM=$(echo $igpu | cut -d " " -f1)
ifreM=$(echo $igpu | cut -d " " -f2)
iuseM=$(expr $itotM - $ifreM)
iperc=$(echo "$iuseM * 100 / $itotM" | bc)
iuseM=$(echo $iuseM | numfmt --to si --from-unit=M --format "%f")
itotM=$(echo $itotM | numfmt --to si --from-unit=M --format "%f")
# printf "iGᵖ %s%% (%sB / %sB)" $iperc $iuseM $itotM

dtotM=$(nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits)
duseM=$(nvidia-smi --query-gpu=memory.used --format=csv,noheader,nounits)
dperc=$(echo "$duseM * 100 / $dtotM" | bc)

printf "RY: %s%%  NV: %s%%" $iperc $dperc