#! /usr/bin/env bash

BAR_HEIGHT=20  # polybar height
BORDER_SIZE=8  # border size from your wm settings
YAD_WIDTH=100  # 222 is minimum possible value
YAD_HEIGHT=130 # 193 is minimum possible value

if [ "$(xdotool getwindowfocus getwindowname)" = "calendar" ]; then
    exit 0
fi

eval "$(xdotool getmouselocation --shell)"
eval "$(xdotool getdisplaygeometry --shell)"

# X
if [ "$((X + YAD_WIDTH / 2 + BORDER_SIZE))" -gt "$WIDTH" ]; then #Right side
    : $((pos_x = WIDTH - YAD_WIDTH - BORDER_SIZE))
elif [ "$((X - YAD_WIDTH / 2 - BORDER_SIZE))" -lt 0 ]; then #Left side
    : $((pos_x = BORDER_SIZE))
else #Center
    : $((pos_x = X - YAD_WIDTH / 2))
fi

# Y
if [ "$Y" -gt "$((HEIGHT / 2))" ]; then #Bottom
    : $((pos_y = HEIGHT - YAD_HEIGHT - BAR_HEIGHT - BORDER_SIZE))
else #Top
    : $((pos_y = BAR_HEIGHT + BORDER_SIZE))
fi

yad --form --title="optimus switcher" --borders=0 --undecorated --close-on-unfocus \
    --posx="$pos_x" --posy="$pos_y" --no-buttons --width="100" --height="130"\
    --field="integrated:BTN" 'optimus-manager --no-confirm --switch integrated' \
    --field="hybrid:BTN" 'optimus-manager --no-confirm --switch hybrid' \
    --field="nvidia:BTN" 'optimus-manager --no-confirm --switch nvidia' \
