#! /usr/bin/env bash

if rfkill list wlan | grep -q 'Soft blocked: no'; then
	status="on"
else
	status="off"
fi

INT="wlan0"

case "$1" in
	--toggle)
		if [ "$status" = "off" ]; then
			sudo rfkill unblock wlan
			notify-send "Turned on WiFi."
		else
			sudo rfkill block wlan
			notify-send "Turned off WiFi."
		fi
		;;
	*)
		if [ "$status" = "off" ]; then
			echo "󰖪"
		elif [ "$status" = "on" ]; then
			if nmcli | grep -q "$INT: connected"; then
				echo "󱚻"
			else
				echo "󰖩"
			fi
		fi
		;;
esac
